/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    max
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Main_max
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
